title: Wulan Maiduo  
tagline: Here is Wulan Maiduo - Personal Profile (Ling Cage Season 2) 
description: Explore the personal profile of Wulan Maiduo, the brave spear master from Dragon Bone Village in Ling Cage Season 2, including her abilities, story and bond with her falcon companion Chagai.  

url: https://sgldbang.github.io

owner:
  name: sgldbang
  avatar: sgldbang.jpg

  github: sgldbang
  bilibili: 3546705421142300



# --------------------------------------------------
#  SEARCH-ENGINE VERIFICATION & ANALYTICS
# --------------------------------------------------
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"
# bing_verify: ""    # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# google_analytics: "G-XXXXXXX"                                 # GA-4 property ID


# --------------------------------------------------
#  TOP NAVIGATION BAR
#  `external: true` opens the link in a new tab.
# --------------------------------------------------
links:
  - title: About Wulan Maiduo
    url: /
  # - title: Abilities
  #   url: /hobbies/
  - title: Story & Plot
    url: /story/
  - title: Pet (Chagai)
    url: /pet/
  - title: Hobbies
    url: /hobbies/



# BUILD & RENDERING OPTIONS
timezone: Asia/Shanghai
future: true
highlighter: rouge
markdown: kramdown


# PERMALINK STRUCTURE

# permalink: /:categories/:title

# KRAMDOWN (Markdown engine) SETTINGS
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

